"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 13:39:44.176062
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('website_found', sa.String(length=500), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('registry_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('assigned_to', sa.String(length=64), nullable=True),
    sa.Column('fix_count', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('disqualify_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_assigned_to', ['assigned_to'], unique=False)
        batch_op.create_index('ix_leads_scope_status', ['scope', 'status'], unique=False)

    op.create_table('suppression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppression_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppression_email'), ['email'], unique=False)

    op.create_table('ad_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('ad_library_url', sa.String(length=500), nullable=True),
    sa.Column('screenshot_paths', sa.JSON(), nullable=False),
    sa.Column('ad_copy', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_captures_lead_id'), ['lead_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_lead_id'), ['lead_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_lead_id'), ['lead_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_ts'), ['ts'], unique=False)

    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_lead_id'), ['lead_id'], unique=False)

    op.create_table('qa_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('artifact_version', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_reports_lead_id'), ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_reports_lead_id'))

    op.drop_table('qa_reports')
    with op.batch_alter_table('outreach', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_lead_id'))

    op.drop_table('outreach')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_ts'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_ts'))
        batch_op.drop_index(batch_op.f('ix_events_lead_id'))

    op.drop_table('events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_lead_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_lead_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('ad_captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_captures_lead_id'))

    op.drop_table('ad_captures')
    with op.batch_alter_table('suppression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppression_email'))
        batch_op.drop_index(batch_op.f('ix_suppression_domain'))

    op.drop_table('suppression')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_scope_status')
        batch_op.drop_index('ix_leads_assigned_to')

    op.drop_table('leads')
    # ### end Alembic commands ###
